// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEKcBs39KbIii-Hcpj4feYGTMQvL29ORU',
    appId: '1:958809412045:web:226158a702998a63c57484',
    messagingSenderId: '958809412045',
    projectId: 'cacapp-3a771',
    authDomain: 'cacapp-3a771.firebaseapp.com',
    storageBucket: 'cacapp-3a771.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS-e95lWlY1nlwf4yK9Rzl710WFow0sls',
    appId: '1:958809412045:android:08c08350befaac04c57484',
    messagingSenderId: '958809412045',
    projectId: 'cacapp-3a771',
    storageBucket: 'cacapp-3a771.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3baVUSEieG-spa_JzE4erma4gaMDMCYE',
    appId: '1:958809412045:ios:3943af809909253bc57484',
    messagingSenderId: '958809412045',
    projectId: 'cacapp-3a771',
    storageBucket: 'cacapp-3a771.firebasestorage.app',
    iosClientId: '958809412045-4pfuo3okr0gjtj50fps38sl66ffl59ss.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3baVUSEieG-spa_JzE4erma4gaMDMCYE',
    appId: '1:958809412045:ios:3943af809909253bc57484',
    messagingSenderId: '958809412045',
    projectId: 'cacapp-3a771',
    storageBucket: 'cacapp-3a771.firebasestorage.app',
    iosClientId: '958809412045-4pfuo3okr0gjtj50fps38sl66ffl59ss.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );
}
